#!/bin/sh
# Copyright 2022 Ryan SVIHLA

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# script/bootstrap: Resolve all dependencies that the application requires to
#       
set -e

cd "$(dirname "$0")/.."
echo "checking if rustc is present"
if ! command -v rustc &> /dev/null
then
    echo "rustc could not be found installing rustup"
    curl https://sh.rustup.rs -sSf | sh -s -- -y
fi


echo "checking if rustfmt is present"
if ! command -v rustmt &> /dev/null
then
    echo "rustfmt could not be found installing"
    rustup component add rustfmt
fi